
SRCS = ujprog.c
INCLUDES = -I/usr/local/include
LIBDIRS = -L/usr/local/lib
CFLAGS += -Wall ${INCLUDES}
FTLIB = /usr/local/lib/libftdi.a

ujprog:	${SRCS}
	${CC} ${CFLAGS} ${LIBDIRS} -lusb ${SRCS} ${FTLIB} -o ujprog

flash:	ft232r_flash.c
	${CC} ${CFLAGS} ${LIBDIRS} -lusb ft232r_flash.c ${FTLIB} -o ft232r_flash
	
install: ujprog
	install -m 4755 ujprog /usr/local/bin

clean:
	rm -f ujprog ujprog.o

depend:
	mkdep ${INCLUDES} ${SRCS}
